/*
 * scripts/create_admin_and_seed.js
 *
 * Usage (run server-side only):
 *  SUPABASE_URL=https://xxxxx.supabase.co SUPABASE_SERVICE_ROLE_KEY=ey... ADMIN_EMAIL=admin@simjs.com ADMIN_PASSWORD=StrongPass123! node scripts/create_admin_and_seed.js
 *
 * This script:
 *  - Creates an auth user via Supabase Admin API (requires SERVICE ROLE KEY)
 *  - Inserts a profile row (profiles table) for that user
 *  - Inserts example content (page + post) and an example partner
 *
 * SECURITY: The service role key has full privileges and must never be exposed to client-side.
 */

import fetch from 'node-fetch';
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || 'admin@simjs.com';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'ChangeMe123!';

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error('Error: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set as environment variables.');
  process.exit(1);
}

async function createAuthUser(email, password) {
  const url = `${SUPABASE_URL}/admin/v1/users`;
  const body = {
    email,
    password,
    email_confirm: true
  };

  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${SERVICE_ROLE_KEY}`,
      apikey: SERVICE_ROLE_KEY
    },
    body: JSON.stringify(body)
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Admin API create user failed: ${res.status} ${text}`);
  }

  const data = await res.json();
  return data;
}

async function run() {
  try {
    console.log('Starting admin creation + seed (server-side)...');

    // 1) create auth user
    console.log(`Creating auth user: ${ADMIN_EMAIL}`);
    const created = await createAuthUser(ADMIN_EMAIL, ADMIN_PASSWORD);
    // created contains user object
    const userId = created.id || created.user?.id;
    if (!userId) {
      console.error('Failed to retrieve user id from admin create response:', created);
      process.exit(1);
    }

    console.log('Created auth user id =', userId);

    // 2) initialize supabase client with service role key (can bypass RLS)
    const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, { auth: { persistSession: false } });

    // 3) insert profile
    console.log('Inserting profile...');
    const { error: pErr } = await supabase.from('profiles').insert([{ id: userId, username: 'admin', full_name: 'Administrador SIMJS', role: 'admin', newsletter: true }]);
    if (pErr) throw pErr;
    console.log('Profile inserted.');

    // 4) insert sample content
    console.log('Inserting sample content...');
    const page = {
      id: undefined, // will be generated by DB
      type: 'page',
      title: 'Página de Exemplo',
      slug: 'pagina-exemplo',
      excerpt: 'Página de exemplo criada pelo seed',
      body: 'Conteúdo de exemplo para a página inicial.',
      author_id: userId,
      status: 'published',
      tags: ['example','page']
    };
    const post = {
      type: 'post',
      title: 'Notícia de Lançamento',
      slug: 'noticia-lancamento',
      excerpt: 'Exemplo de post',
      body: 'Este é um post de exemplo publicado pelo administrador.',
      author_id: userId,
      status: 'published',
      tags: ['news','announcement']
    };
    const { error: cErr } = await supabase.from('content').insert([page, post]);
    if (cErr) throw cErr;
    console.log('Sample content inserted.');

    // 5) insert sample partner
    console.log('Inserting sample partner...');
    const { error: partErr } = await supabase.from('partners').insert([{ profile_id: userId, company_name: 'SIMJS Exemplo Lda', contact_name: 'Responsavel Exemplo', email: 'parceiro@example.com', phone: '+244 922 000 000', website: 'https://www.example-parceiro.com', status: 'approved' }]);
    if (partErr) throw partErr;
    console.log('Sample partner inserted.');

    console.log('\nDone. Verifications:');
    console.log(`SELECT * FROM profiles WHERE id = '${userId}';`);
    console.log('SELECT * FROM content ORDER BY created_at DESC LIMIT 10;');
    console.log('SELECT * FROM partners ORDER BY created_at DESC LIMIT 10;');

    console.log('\nNOTE: This script uses the service role key and must run server-side only.');
  } catch (err) {
    console.error('Error during seed:', err);
    process.exit(1);
  }
}

import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const isMain = process.argv[1] === __filename;
if (isMain) await run();
